
server:
 port: 9002
 
 
#mysql server url username and password and application name and zipkin server url id 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: USER-SERVICE 
  zipkin:
   base-url: http://localhost:9411/  
    
    
    
#eurka client settings
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
 instance:
  hostname: localhost      
  
  
#standar configuration for actuator
management:
 health:
  circuitbreakers:
   enabled: true
 endpoints:
  web:
   exposure:
     include: health
 endpoint:
  health:
   Showdetatis: always  
  
  
#resilience4j 
resilience4j:
 circuitbreaker:
  instances:
   serviceUser: 
    registerHealthIndicator: true
    eventConsumerBufferSize: 10
    failureRateThreshold: 50
    minimumNumberOfCalls: 5
    automaticTransitionFromOpenToHal fOpenEnabled: true
    waitDurationInOpenState: 5s
    permittedNumberOfCallsInHalfOpenState: 3
    slidingWindowSize: 10
    slidingWindowType: COUNT_BASED  
  
  